repos:
  - repo: https://github.com/jwbennet/lint-staged-pre-commit-hook
    rev: v1.0.0
    hooks:
      - id: lint-staged
        stages: [pre-commit]
        additional_dependencies: ["prettier"]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
